/*
 *      Author: Mohamed Newir
 *      Created on: Aug 5, 2025
 *      File name: Timers_config.h
 *      Description:
 *      			shared data types between timers
 */


#ifndef MCAL_TIMERS_DRIVER_INCLUDE_TIMERS_CONFIG_H_
#define MCAL_TIMERS_DRIVER_INCLUDE_TIMERS_CONFIG_H_

/* WAVE FORM GENERATION MODE SELECT */
typedef enum{
	NORMAL, /* OVER FLOW MODE */
	PWM_PHASE_CORRECT, CTC, FAST_PWM
}WAVE_FORM_GENERATION_MODE_SELECT;

/* FAST PWM MODE SELECT */
typedef enum{
	FAST_PWM_NORMAL, /* OCO disconnected */
	RESERVED, NON_INVERTING_MODE, INVERTING_MODE
}FAST_PWM_MODE_SELECT;

/* PHASE CORRECT PWM MODE SELECT */
/*
typedef enum{
	NORMAL,
	RESERVED, CLEAR_OC0, SET_OC0
}PHASE_CORRECT_PWM_MODE_SELECT;
*/

/* CLOCK SELECT */
typedef enum{
	NO_CLOCK, NO_PRESCALER, PRESCALER_8, PRESCALER_32, PRESCALER_64,
	PRESCALER_128, PRESCALER_256, PRESCALER_1024
}CLOCK_SELECT;

#endif /* MCAL_TIMERS_DRIVER_INCLUDE_TIMERS_CONFIG_H_ */
